const Songs = [
    {
        name: 'Night City',
        artist: 'Tobie',
        img: 'https://i1.sndcdn.com/artworks-MCj2k4p3kj8vmoDk-hedYLQ-t500x500.jpg',
        audio: '/asset/audio/nightcity.mp3',
        plays: '1.6M',
        hearts: '371K',
        reposts: '308',
        comments: '192',
        uploader: 'Tobie ft. hnhngan',
    },
    {
        name: 'Anh Biết',
        artist: 'Xám x D.Blue',
        img: 'https://i.ytimg.com/vi/5qdBvucGwhQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAZ6dkU9sT-bZTdbVtkEA10F7kzzw',
        audio: '/asset/audio/anhbiet.mp3',
        plays: '5.91M',
        hearts: '47.9K',
        reposts: '1,624',
        comments: '1,151',
        uploader: 'D.Blue',
    },
    {
        name: 'Anh Đâu Đấy',
        artist: 'Reddy x Freak D',
        img: 'https://i.ytimg.com/vi/UcnFdChhHs8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKCS7Pq5Lj3b8sO4pNY9FahHcHMA',
        audio: '/asset/audio/anhdauday.mp3',
        plays: '2.21M',
        hearts: '15.9K',
        reposts: '381',
        comments: '213',
        uploader: 'KunN',
    },
    {
        name: 'Bước Qua Mùa Cô Đơn',
        artist: 'Vũ',
        img: 'https://i.ytimg.com/vi/n6Pnzi6r9NU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDNX9JaeLHOGU7SAT-T_DYlOhPmPg',
        audio: '/asset/audio/buocquamuacodon.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'Vũ',
    },
    {
        name: 'Cliché',
        artist: 'mxmtoon',
        img: 'https://i.ytimg.com/vi/IGPqSepfbG0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAI6jLdPgG9H3kzH5qt46xXg5GjWg',
        audio: '/asset/audio/cliche.mp3',
        plays: '1.6M',
        hearts: '371K',
        reposts: '308',
        comments: '192',
        uploader: 'mxmtoon',
    },
    {
        name: 'Có Em',
        artist: 'Madihu x Low G',
        img: 'https://i.ytimg.com/vi/DcCISK3sCYg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB3PQ9UkHd72gvrv1Rae2GDmh5y6g',
        audio: '/asset/audio/coem.mp3',
        plays: '5.6M',
        hearts: '56.4K',
        reposts: '545',
        comments: '379',
        uploader: 'DuckDaz.',
    },
    {
        name: 'Crush 2',
        artist: 'W/n ft ( Tez, Tien )',
        img: 'https://i1.sndcdn.com/artworks-000648366157-rzxibj-t500x500.jpg',
        audio: '/asset/audio/crush2.mp3',
        plays: '2.04M',
        hearts: '22.6K',
        reposts: '724',
        comments: '351',
        uploader: 'W/n',
    },
    {
        name: 'Đêm Trong Veo',
        artist: 'RPT Groovie x RPT GONZO',
        img: 'https://i.ytimg.com/vi/xiehRbeUaYs/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB1AaAAuADigIMCAAQARhlIFooXTAP&rs=AOn4CLC42qB50clpMYvITbQ7PvKEVV2wMg',
        audio: '/asset/audio/demtrongveo.mp3',
        plays: '2.47M',
        hearts: '22.6K',
        reposts: '25',
        comments: '8',
        uploader: 'Taruss',
    },
    {
        name: 'Em',
        artist: 'FlexEtCheck + hairan',
        img: 'https://i.ytimg.com/vi/TyL3DXpEsVE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDy5MHhAWUlUZigt-CT2bO8JekesA',
        audio: '/asset/audio/em.mp3',
        plays: '957K',
        hearts: '10.4K',
        reposts: '863',
        comments: '113',
        uploader: 'checkurplayers',
    },
    {
        name: 'Em Là Nhất',
        artist: 'kis x Hoàng KayLee x Yahy',
        img: 'https://i.ytimg.com/vi/J3RhbVkVdbU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLARoIoN_dZw9Av6dnPbxTK-Tk7t2g',
        audio: '/asset/audio/emlanhat.mp3',
        plays: '5.91M',
        hearts: '47.9K',
        reposts: '1,624',
        comments: '1,151',
        uploader: 'kis',
    },
    {
        name: 'Flexin trên CircleK ',
        artist: 'LowG',
        img: 'https://i.ytimg.com/vi/5efrC3vLH_U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgY5OufRVDsMD9notrUQkUh7qANQ',
        audio: '/asset/audio/flexing.mp3',
        plays: '4.3M',
        hearts: '46.6K',
        reposts: '1,259',
        comments: '909',
        uploader: 'Rap Nhà Làm',
    },
    {
        name: 'Forget Me Now',
        artist: 'Fishy ft. Trí Dũng',
        img: 'https://i.ytimg.com/vi/Qy_ADdVXv6Q/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBuM9bnuRAt_nB_vtkur2EvFdyDmg',
        audio: '/asset/audio/forgetmenow.mp3',
        plays: '5.91M',
        hearts: '47.9K',
        reposts: '1,624',
        comments: '1,151',
        uploader: 'fishy',
    },
    {
        name: 'Ghé Qua',
        artist: 'BCTM',
        img: 'https://i.ytimg.com/vi/zEWSSod0zTY/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqvZa1nbDL-jeLmBvggFqJhB99xw',
        audio: '/asset/audio/ghequa.mp3',
        plays: '2.47M',
        hearts: '22.6K',
        reposts: '25',
        comments: '8',
        uploader: 'Dick - Bạn Có Tài Mà',
    },
    {
        name: 'Không Phải Lời Tỏ Tình',
        artist: '1ng',
        img: 'https://i.ytimg.com/vi/fvTBSgY9H3U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC6K6vEnMsQE8uVghsqlx19fYYC7g',
        audio: '/asset/audio/khongphailoitotinh.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'iKaj',
    },
    {
        name: 'Lời Tạm Biệt Chưa Nói',
        artist: 'GREY D & ORANGE',
        img: 'https://i.ytimg.com/vi/sdBdWCeYtBE/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhLIFgoZTAP&rs=AOn4CLDpFDk20f8HMCg7x-fbH-d6rkP60Q',
        audio: '/asset/audio/loitambietchuanoi.mp3',
        plays: '2.47M',
        hearts: '22.6K',
        reposts: '25',
        comments: '8',
        uploader: 'THH',
    },
    {
        name: 'Lời Yêu Ngây Dại',
        artist: 'Kha',
        img: 'https://i.ytimg.com/vi/UBv-GcD3jHE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB-BJnK_mk0DR8AQrbuK5v6Kb6YRw',
        audio: '/asset/audio/loiyeungaydai.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'KHA',
    },
    {
        name: 'Mascara',
        artist: 'Chillies x BLAZE',
        img: 'https://i.ytimg.com/vi/ntEoGvhoVac/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAkcHt4siVQtJwRL6DY3t1a_ivDKw',
        audio: '/asset/audio/mascara.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'Shaun',
    },
    {
        name: 'Nghe Em',
        artist: 'Thinh Suy',
        img: 'https://i.ytimg.com/vi/EN1bplFXfIw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD44BvyeBeT8mVYE8DSdtNJRie37A',
        audio: '/asset/audio/ngheem.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'dungbunnua',
    },
    {
        name: 'Ngừng Mơ',
        artist: 'An Cover',
        img: 'https://i.ytimg.com/vi/Cxm8Md8yAAY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAy692lsZFbIFoSnLrJu_pMhjKoRg',
        audio: '/asset/audio/ngungmo.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'nhn',
    },
    {
        name: 'Ngủ Sớm Đi Em',
        artist: 'DucMinh',
        img: 'https://i.ytimg.com/vi/wdQoVMlVMGY/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB1AaAAuADigIMCAAQARhJIE4oZTAP&rs=AOn4CLDxt1Grkh2gWAT1pKCOMnLAwDDJnw',
        audio: '/asset/audio/ngusomdiem.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'DucMinh',
    },
    {
        name: 'Nhật Thực',
        artist: 'Cáo x Luyngram @37 Sound ♪',
        img: 'https://i.ytimg.com/vi/B8Mu9dMJO5k/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB1AaAAuADigIMCAAQARhyIEgoKjAP&rs=AOn4CLAxM1dfTTV02x25fgLx9YC3OqylCQ',
        audio: '/asset/audio/nhatthuc.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'DFoxie37 aka Cáo',
    },
    {
        name: 'Oishi',
        artist: 'hieuthuhai ft. thetumeymtu',
        img: 'https://i.ytimg.com/vi/DL1MddcifNk/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBzgWAAtAFigIMCAAQARhlIEkoVDAP&rs=AOn4CLDmSPUIcw2bZ1bT4Ma9sGR279hTNA',
        audio: '/asset/audio/oishi.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'HIEUTHUHAI',
    },
    {
        name: 'okeokeoke',
        artist: 'Low G',
        img: 'https://i.ytimg.com/vi/TaZTsgc_bg8/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVTBWbP1WRr1l9xehipi2_4px7YQ',
        audio: '/asset/audio/okokok.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'Muwa',
    },
    {
        name: 'Simple Love',
        artist: 'W/n - Cover Duongg , Titie',
        img: 'https://i.ytimg.com/vi/fHfirUHkjQA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCisjf_OcHUgjLfTtjdgPnwxG2roQ',
        audio: '/asset/audio/simplelove.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'W/n',
    },
    {
        name: 'Sống Cho Hết Đời Thanh Xuân',
        artist: 'BCTM',
        img: 'https://i.ytimg.com/vi/mmuBhumw4Nk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIGHFGgGoqiIYk-IfxVT4qHoLVUg',
        audio: '/asset/audio/songchohetdoithanhxuan.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'BCTM',
    },
    {
        name: 'Tình Ca Tình Ta',
        artist: 'kis',
        img: 'https://i.ytimg.com/vi/R0jbjEX0dBY/hqdefault.jpg?sqp=-oaymwE2COADEI4CSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgBhAaAAuADigIMCAAQARhlIFgoSjAP&rs=AOn4CLCWLaQ5xYKWhiWMPWJzGDzBug31VQ',
        audio: '/asset/audio/tinhcatinhta.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'kis',
    },
    {
        name: 'Yêu Lại Chút Thôi',
        artist: 'Clow x Linh Thộn',
        img: 'https://i.ytimg.com/vi/oHc5xjM4bA4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDKyMY9mcA5cHofLOKFq3SHbKTGrw',
        audio: '/asset/audio/yeulaichutthoi.mp3',
        plays: '105K',
        hearts: '171K',
        reposts: '231',
        comments: '153',
        uploader: 'Clow',
    },
];
export default Songs;
